#!/usr/bin/env perl
use strict;
use warnings;

use Proclet::Declare;
use Getopt::Long;

GetOptions(
    'kytprof'  => \my $kytprof,
);

color;
env(
    LM_DEBUG => 1,
);

service('web', 'plackup', 'app.psgi');

run;
