#!/usr/bin/env perl
use strict;
use warnings;

use File::Spec;
use File::Basename;
use lib File::Spec->catdir(dirname(__FILE__), 'extlib', 'lib', 'perl5');
use lib File::Spec->catdir(dirname(__FILE__), 'lib');

use Proclet::Declare;
use Getopt::Long;
use MyApp::Config;

GetOptions(
    'kytprof'  => \my $kytprof,
);

color;
env(
    LM_DEBUG => 1,
);

my @opts = (
    $kytprof ? '-MDevel::KYTProf' : (),
);

service('web' => 'plackup', '-r',
    '-p' =>  config->param('boostrap')->{web}->{port},
    '-a' =>  'dev.psgi',
    '-R' => './templates,./config,./dev.psgi,',
    @opts
);

service('memcached' => 'memcached',
    '-p', config->param('boostrap')->{memcached}->{port}
);

run;
