#!/usr/bin/env perl
use strict;
use warnings;

use File::Spec;
use File::Basename;
use lib File::Spec->catdir(dirname(__FILE__), 'extlib', 'lib', 'perl5');
use lib File::Spec->catdir(dirname(__FILE__), 'lib');

use Proclet::Declare;
use Getopt::Long;
use MyApp::Config;

GetOptions(
    'kytprof'  => \my $kytprof,
);

color;
env(
    LM_DEBUG => 1,
);

service('web' => 'plackup', '-r',
    '-a' =>  'dev.psgi',
    '-R' => './templates,./config,./dev.psgi,',
    $kytprof ? '-MDevel::KYTProf' : (),
    @{config->param('boostrap')->{web} || []},
);

service('memcached' => 'memcached',
    @{config->param('boostrap')->{memcached} || []},
);

run;
